import { branchSeedData } from "@/modules/branches/constants/branches.constants";
import { serviceSeedData } from "@/modules/services/constants/services.constants";
import type {
  AppointmentCancellationRecord,
  AppointmentCitizenSummary,
  AppointmentRecord,
  AppointmentSlotLookupRecord,
  AppointmentStaffUserSummary,
  AppointmentStatus,
  ListAppointmentsQuery,
} from "@/modules/appointments/types/appointment.types";

export const appointmentsQueryKeys = {
  all: ["appointments"] as const,
  list: (
    tenantId?: string,
    query: ListAppointmentsQuery = DEFAULT_LIST_APPOINTMENTS_QUERY,
  ) => {
    const normalized = normalizeListAppointmentsQuery(query);

    return [
      ...appointmentsQueryKeys.all,
      "list",
      tenantId ?? "all",
      normalized.status,
      normalized.serviceId,
      normalized.branchId,
      normalized.citizenId,
      normalized.dateFrom,
      normalized.dateTo,
      normalized.search,
    ] as const;
  },
  detail: (tenantId?: string, appointmentId?: string) =>
    [
      ...appointmentsQueryKeys.all,
      "detail",
      tenantId ?? "all",
      appointmentId ?? "unknown",
    ] as const,
  slots: (
    tenantId?: string,
    branchId?: string,
    serviceId?: string,
    date?: string,
  ) =>
    [
      ...appointmentsQueryKeys.all,
      "slots",
      tenantId ?? "all",
      branchId ?? "none",
      serviceId ?? "none",
      date ?? "none",
    ] as const,
};

export const DEFAULT_LIST_APPOINTMENTS_QUERY: ListAppointmentsQuery = {};

export const appointmentStatusFlow: Record<
  AppointmentStatus,
  AppointmentStatus[]
> = {
  PENDING: ["CONFIRMED", "CANCELLED"],
  CONFIRMED: ["CHECKED_IN", "NO_SHOW", "CANCELLED"],
  CHECKED_IN: ["IN_PROGRESS"],
  IN_PROGRESS: ["COMPLETED"],
  COMPLETED: [],
  CANCELLED: [],
  NO_SHOW: [],
  RESCHEDULED: [],
};

export function normalizeListAppointmentsQuery(
  query: ListAppointmentsQuery = {},
) {
  return {
    status: query.status ?? "all",
    serviceId: query.serviceId?.trim() ?? "",
    branchId: query.branchId?.trim() ?? "",
    citizenId: query.citizenId?.trim() ?? "",
    dateFrom: query.dateFrom?.trim() ?? "",
    dateTo: query.dateTo?.trim() ?? "",
    search: query.search?.trim() ?? "",
  } as const;
}

const appointmentStaffSeedData: AppointmentStaffUserSummary[] = [
  {
    id: "staff_operator_camila",
    branchId: branchSeedData[0]?.id ?? null,
    email: "camila.operator@turnix.local",
    firstName: "Camila",
    lastName: "Rojas",
    role: "OPERATOR",
  },
];

export const appointmentCitizenSeedData: AppointmentCitizenSummary[] = [
  {
    id: "cit_ana_gonzalez",
    firstName: "Ana",
    lastName: "Gonzalez",
    email: "ana.gonzalez@example.com",
    phone: "+56911112222",
    documentType: "RUT",
    documentNumber: "12.345.678-9",
  },
  {
    id: "cit_mario_soto",
    firstName: "Mario",
    lastName: "Soto",
    email: "mario.soto@example.com",
    phone: "+56933334444",
    documentType: "RUT",
    documentNumber: "14.567.890-1",
  },
  {
    id: "cit_paula_vega",
    firstName: "Paula",
    lastName: "Vega",
    email: "paula.vega@example.com",
    phone: "+56955556666",
    documentType: null,
    documentNumber: null,
  },
];

export const appointmentSlotSeedData: AppointmentSlotLookupRecord[] = [
  {
    id: "slot_backoffice_0900",
    slotDate: "2026-04-06T00:00:00.000Z",
    startsAt: "2026-04-06T12:00:00.000Z",
    endsAt: "2026-04-06T12:30:00.000Z",
    capacity: 1,
    reservedCount: 0,
    status: "OPEN",
    branchId: branchSeedData[0]?.id ?? "br_main_office",
    serviceId: serviceSeedData[0]?.id ?? "svc_civil_records",
    staffUserId: appointmentStaffSeedData[0]?.id ?? null,
  },
  {
    id: "slot_backoffice_0930",
    slotDate: "2026-04-06T00:00:00.000Z",
    startsAt: "2026-04-06T12:30:00.000Z",
    endsAt: "2026-04-06T13:00:00.000Z",
    capacity: 1,
    reservedCount: 1,
    status: "FULL",
    branchId: branchSeedData[0]?.id ?? "br_main_office",
    serviceId: serviceSeedData[0]?.id ?? "svc_civil_records",
    staffUserId: appointmentStaffSeedData[0]?.id ?? null,
  },
  {
    id: "slot_backoffice_1030",
    slotDate: "2026-04-06T00:00:00.000Z",
    startsAt: "2026-04-06T13:30:00.000Z",
    endsAt: "2026-04-06T14:00:00.000Z",
    capacity: 2,
    reservedCount: 1,
    status: "OPEN",
    branchId: branchSeedData[1]?.id ?? "br_north_center",
    serviceId: serviceSeedData[1]?.id ?? "svc_building_permits",
    staffUserId: null,
  },
  {
    id: "slot_backoffice_1430",
    slotDate: "2026-04-07T00:00:00.000Z",
    startsAt: "2026-04-07T17:30:00.000Z",
    endsAt: "2026-04-07T18:15:00.000Z",
    capacity: 3,
    reservedCount: 1,
    status: "OPEN",
    branchId: branchSeedData[0]?.id ?? "br_main_office",
    serviceId: serviceSeedData[2]?.id ?? "svc_social_programs",
    staffUserId: null,
  },
];

function createCancellationSeed(
  overrides: Partial<AppointmentCancellationRecord>,
): AppointmentCancellationRecord {
  return {
    id: "cancel_001",
    appointmentId: "apt_004",
    cancelledByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
    reason: "Citizen requested cancellation",
    details: "Citizen called to confirm they could not attend the appointment.",
    cancelledAt: "2026-04-04T18:20:00.000Z",
    cancelledByStaffUser: appointmentStaffSeedData[0] ?? null,
    ...overrides,
  };
}

export const appointmentSeedData: AppointmentRecord[] = [
  {
    id: "apt_001",
    tenantId: "tenant_municipal_services",
    branchId: appointmentSlotSeedData[0]?.branchId ?? "br_main_office",
    serviceId: appointmentSlotSeedData[0]?.serviceId ?? "svc_civil_records",
    citizenId: appointmentCitizenSeedData[0]?.id ?? "cit_ana_gonzalez",
    staffUserId: appointmentSlotSeedData[0]?.staffUserId ?? null,
    slotId: appointmentSlotSeedData[0]?.id ?? "slot_backoffice_0900",
    code: "APT-20260406-A1B2C3",
    source: "STAFF",
    status: "CONFIRMED",
    scheduledStart: appointmentSlotSeedData[0]?.startsAt ?? "2026-04-06T12:00:00.000Z",
    scheduledEnd: appointmentSlotSeedData[0]?.endsAt ?? "2026-04-06T12:30:00.000Z",
    citizenNotes: "Needs document review at arrival.",
    internalNotes: "Priority attention requested by the branch team.",
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    createdAt: "2026-04-01T14:00:00.000Z",
    updatedAt: "2026-04-02T14:00:00.000Z",
    branch: {
      id: branchSeedData[0]?.id ?? "br_main_office",
      slug: branchSeedData[0]?.slug ?? "main-office",
      name: branchSeedData[0]?.name ?? "Main Office",
    },
    service: {
      id: serviceSeedData[0]?.id ?? "svc_civil_records",
      slug: serviceSeedData[0]?.slug ?? "civil-records-assistance",
      name: serviceSeedData[0]?.name ?? "Civil Records Assistance",
      visibility: serviceSeedData[0]?.visibility ?? "PUBLIC",
      mode: serviceSeedData[0]?.mode ?? "IN_PERSON",
      durationMinutes: serviceSeedData[0]?.durationMinutes ?? 20,
    },
    citizen: appointmentCitizenSeedData[0]!,
    slot: appointmentSlotSeedData[0]!,
    staffUser: appointmentStaffSeedData[0] ?? null,
    statusHistory: [
      {
        id: "history_001",
        appointmentId: "apt_001",
        fromStatus: null,
        toStatus: "CONFIRMED",
        note: "Appointment created by backoffice operator.",
        metadata: {
          source: "STAFF",
        },
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-01T14:00:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
    ],
  },
  {
    id: "apt_002",
    tenantId: "tenant_municipal_services",
    branchId: appointmentSlotSeedData[2]?.branchId ?? "br_north_center",
    serviceId: appointmentSlotSeedData[2]?.serviceId ?? "svc_building_permits",
    citizenId: appointmentCitizenSeedData[1]?.id ?? "cit_mario_soto",
    staffUserId: null,
    slotId: appointmentSlotSeedData[2]?.id ?? "slot_backoffice_1030",
    code: "APT-20260406-D4E5F6",
    source: "WEB",
    status: "PENDING",
    scheduledStart: appointmentSlotSeedData[2]?.startsAt ?? "2026-04-06T13:30:00.000Z",
    scheduledEnd: appointmentSlotSeedData[2]?.endsAt ?? "2026-04-06T14:00:00.000Z",
    citizenNotes: null,
    internalNotes: "Pending operator confirmation after intake review.",
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    createdAt: "2026-04-03T09:45:00.000Z",
    updatedAt: "2026-04-03T09:45:00.000Z",
    branch: {
      id: branchSeedData[1]?.id ?? "br_north_center",
      slug: branchSeedData[1]?.slug ?? "north-service-center",
      name: branchSeedData[1]?.name ?? "North Service Center",
    },
    service: {
      id: serviceSeedData[1]?.id ?? "svc_building_permits",
      slug: serviceSeedData[1]?.slug ?? "building-permit-orientation",
      name: serviceSeedData[1]?.name ?? "Building Permit Orientation",
      visibility: serviceSeedData[1]?.visibility ?? "INTERNAL",
      mode: serviceSeedData[1]?.mode ?? "IN_PERSON",
      durationMinutes: serviceSeedData[1]?.durationMinutes ?? 30,
    },
    citizen: appointmentCitizenSeedData[1]!,
    slot: appointmentSlotSeedData[2]!,
    staffUser: null,
    statusHistory: [
      {
        id: "history_002",
        appointmentId: "apt_002",
        fromStatus: null,
        toStatus: "PENDING",
        note: "Public flow submitted for internal confirmation.",
        metadata: {
          source: "WEB",
        },
        changedByStaffUserId: null,
        changedAt: "2026-04-03T09:45:00.000Z",
        changedByStaffUser: null,
      },
    ],
  },
  {
    id: "apt_003",
    tenantId: "tenant_municipal_services",
    branchId: appointmentSlotSeedData[3]?.branchId ?? "br_main_office",
    serviceId: appointmentSlotSeedData[3]?.serviceId ?? "svc_social_programs",
    citizenId: appointmentCitizenSeedData[2]?.id ?? "cit_paula_vega",
    staffUserId: null,
    slotId: appointmentSlotSeedData[3]?.id ?? "slot_backoffice_1430",
    code: "APT-20260407-H7I8J9",
    source: "STAFF",
    status: "COMPLETED",
    scheduledStart: appointmentSlotSeedData[3]?.startsAt ?? "2026-04-07T17:30:00.000Z",
    scheduledEnd: appointmentSlotSeedData[3]?.endsAt ?? "2026-04-07T18:15:00.000Z",
    citizenNotes: null,
    internalNotes: "Case closed and documents delivered.",
    checkedInAt: "2026-04-07T17:25:00.000Z",
    completedAt: "2026-04-07T18:10:00.000Z",
    cancelledAt: null,
    createdAt: "2026-04-04T11:20:00.000Z",
    updatedAt: "2026-04-07T18:10:00.000Z",
    branch: {
      id: branchSeedData[0]?.id ?? "br_main_office",
      slug: branchSeedData[0]?.slug ?? "main-office",
      name: branchSeedData[0]?.name ?? "Main Office",
    },
    service: {
      id: serviceSeedData[2]?.id ?? "svc_social_programs",
      slug: serviceSeedData[2]?.slug ?? "social-benefits-guidance",
      name: serviceSeedData[2]?.name ?? "Social Benefits Guidance",
      visibility: serviceSeedData[2]?.visibility ?? "PUBLIC",
      mode: serviceSeedData[2]?.mode ?? "HYBRID",
      durationMinutes: serviceSeedData[2]?.durationMinutes ?? 45,
    },
    citizen: appointmentCitizenSeedData[2]!,
    slot: appointmentSlotSeedData[3]!,
    staffUser: null,
    statusHistory: [
      {
        id: "history_003",
        appointmentId: "apt_003",
        fromStatus: null,
        toStatus: "CONFIRMED",
        note: "Backoffice appointment created.",
        metadata: {
          source: "STAFF",
        },
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-04T11:20:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
      {
        id: "history_004",
        appointmentId: "apt_003",
        fromStatus: "CONFIRMED",
        toStatus: "CHECKED_IN",
        note: "Citizen checked in at front desk.",
        metadata: null,
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-07T17:25:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
      {
        id: "history_005",
        appointmentId: "apt_003",
        fromStatus: "CHECKED_IN",
        toStatus: "IN_PROGRESS",
        note: null,
        metadata: null,
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-07T17:30:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
      {
        id: "history_006",
        appointmentId: "apt_003",
        fromStatus: "IN_PROGRESS",
        toStatus: "COMPLETED",
        note: "Attention completed successfully.",
        metadata: null,
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-07T18:10:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
    ],
  },
  {
    id: "apt_004",
    tenantId: "tenant_municipal_services",
    branchId: appointmentSlotSeedData[0]?.branchId ?? "br_main_office",
    serviceId: appointmentSlotSeedData[0]?.serviceId ?? "svc_civil_records",
    citizenId: appointmentCitizenSeedData[1]?.id ?? "cit_mario_soto",
    staffUserId: appointmentSlotSeedData[0]?.staffUserId ?? null,
    slotId: appointmentSlotSeedData[0]?.id ?? "slot_backoffice_0900",
    code: "APT-20260404-K1L2M3",
    source: "STAFF",
    status: "CANCELLED",
    scheduledStart: "2026-04-08T12:00:00.000Z",
    scheduledEnd: "2026-04-08T12:30:00.000Z",
    citizenNotes: null,
    internalNotes: null,
    checkedInAt: null,
    completedAt: null,
    cancelledAt: "2026-04-04T18:20:00.000Z",
    createdAt: "2026-04-04T10:10:00.000Z",
    updatedAt: "2026-04-04T18:20:00.000Z",
    branch: {
      id: branchSeedData[0]?.id ?? "br_main_office",
      slug: branchSeedData[0]?.slug ?? "main-office",
      name: branchSeedData[0]?.name ?? "Main Office",
    },
    service: {
      id: serviceSeedData[0]?.id ?? "svc_civil_records",
      slug: serviceSeedData[0]?.slug ?? "civil-records-assistance",
      name: serviceSeedData[0]?.name ?? "Civil Records Assistance",
      visibility: serviceSeedData[0]?.visibility ?? "PUBLIC",
      mode: serviceSeedData[0]?.mode ?? "IN_PERSON",
      durationMinutes: serviceSeedData[0]?.durationMinutes ?? 20,
    },
    citizen: appointmentCitizenSeedData[1]!,
    slot: {
      ...appointmentSlotSeedData[0]!,
      startsAt: "2026-04-08T12:00:00.000Z",
      endsAt: "2026-04-08T12:30:00.000Z",
      slotDate: "2026-04-08T00:00:00.000Z",
    },
    staffUser: appointmentStaffSeedData[0] ?? null,
    cancellation: createCancellationSeed({}),
    statusHistory: [
      {
        id: "history_007",
        appointmentId: "apt_004",
        fromStatus: null,
        toStatus: "CONFIRMED",
        note: "Appointment created by backoffice.",
        metadata: {
          source: "STAFF",
        },
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-04T10:10:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
      {
        id: "history_008",
        appointmentId: "apt_004",
        fromStatus: "CONFIRMED",
        toStatus: "CANCELLED",
        note: "Citizen requested cancellation.",
        metadata: null,
        changedByStaffUserId: appointmentStaffSeedData[0]?.id ?? null,
        changedAt: "2026-04-04T18:20:00.000Z",
        changedByStaffUser: appointmentStaffSeedData[0] ?? null,
      },
    ],
  },
];
